build: false
environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"
    
    CONAN_UPLOAD: 1
    CONAN_REFERENCE: "libjpeg-turbo/1.5.3"
    CONAN_USERNAME: "kwallner"
    CONAN_CHANNEL: "stable"
    CONAN_TOTAL_PAGES: 3
    #CONAN_STABLE_BRANCH_PATTERN: "release/*"
    
    matrix:
        - CONAN_CURRENT_PAGE: 1
        - CONAN_CURRENT_PAGE: 2  
        - CONAN_CURRENT_PAGE: 3

install:
  #NASM required if we're not fetching from nuget
  - curl -L -o nasminst.exe http://libgd.blob.core.windows.net/nasm/nasm-2.07-installer.exe && start /wait nasminst.exe /S
  - ps: $env:path="C:\Program Files (x86)\nasm;$($env:path)"
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan_package_tools # It install conan too
  - conan user # It creates the conan data directory

test_script:
  - python build.py
